[pytest]
testpaths =
    tests
norecursedirs =
    tests/_staging
addopts =
    -ra
filterwarnings =
    ignore:numpy.ndarray size changed, may indicate binary incompatibility.:RuntimeWarning
    ignore:registration of accessor .* under name 'rio' .* is overriding a preexisting attribute.*:Warning
